### ISSUE TITLE
Verify Transaction Not Working

### ISSUE THREAD

**Issue by hackzaid** [comfortchambeshi/Wit-MTN-MOMO-API-Python-SDK#1]
Hi @comfortchambeshi Thanks for the great efforts towards this project. I am testing it out and so far things are moving smoothly. However, when it comes to getting the response for verifymomo, I keep getting this error:

`{'message': 'Requested resource was not found.', 'code': 'RESOURCE_NOT_FOUND'}`

Could you be knowing why I am getting this. I have setup everything and on the momopay function, the response is `202` with generated id.

**Comment by comfortchambeshi** [comment]
Hi @hackzaid, sorry for the late response. I also noticed. When in testing mode the best way is to initiate transaction verification just open request to pay calling.

**Comment by comfortchambeshi** [comment]
Hi @hackzaid , we have finally resolved the issue.
